[[Refrigerator-API]]
= Refrigerator-API
해당 냉장고 속 모든 식재료 조회, 냉장고 속 단일 식재료 정보 조회, 냉장고 속 단일 재료 추가, 냉장고 속 단일 재료 정보 수정, 냉장고 속 단일 재료 삭제를 할 수 있는 api입니다.

[[Refrigerator-Get-Single]]
== GET : /api/v1/fridge/ingredient/{id}
=== 냉장고 속 단일 재료 정보를 조회

operation::fridge-get[snippets='path-parameters,response-fields,response-body,http-request,http-response,']

=== 예외 처리
1. 냉장고 id를 입력했는데, 해당하는 냉장고가 존재하지 않을 때

    "message" : "해당하는 냉장고가 존재하지 않습니다."

[[Refrigerator-Get-All]]
== GET : /api/v1/fridge/{userId}
=== 해당 회원의 냉장고 속 모든 식재료를 조회

operation::fridge-get-all[snippets='path-parameters,response-fields,response-body,http-request,http-response,']

=== 예외 처리
1. 유저 id를 입력했는데, 해당하는 유저가 존재하지 않을 때

    "message" : "해당하는 유저 id가 존재하지 않습니다."

2. 냉장고 id를 입력했는데, 해당하는 냉장고에 재료가 존재하지 않을 때 혹은 해당하는 냉장고가 없을 때

    "message" : "해당하는 냉장고에 재료가 존재하지 않습니다."

[[Refrigerator-Add]]
== POST : /api/v1/fridge
=== 냉장고 속 단일 재료 추가

operation::fridge-add[snippets='request-fields,request-body,response-fields,response-body,http-request,http-response,']

=== 예외 처리
1. 재료 id를 입력했는데, 해당하는 재료가 존재하지 않을 때

    "message" : "해당하는 재료가 존재하지 않습니다."

2. 유저 id를 입력했는데, 해당하는 유저가 존재하지 않을 때

    "message" : "해당하는 id가 존재하지 않습니다."

[[Refrigerator-Update]]
== PUT : /api/v1/fridge
=== 냉장고 속 단일 재료 정보 수정
userId, ingredientId는 변하지 않고 expirationDate, quantity, location만 수정 가능합니다.

operation::fridge-update[snippets='request-fields,request-body,response-fields,response-body,http-request,http-response,']

=== 예외 처리
1. 유저 id를 입력했는데, 해당하는 유저가 존재하지 않을 때

    "message" : "해당하는 유저가 존재하지 않습니다."

2. 재료 id를 입력했는데, 해당하는 재료가 존재하지 않을 때

    "message" : "해당하는 재료가 존재하지 않습니다."

3. 냉장고 id를 입력했는데, 해당하는 냉장고가 존재하지 않을 때

    "message" : "해당하는 냉장고가 존재하지 않습니다."

[[Refrigerator-Delete]]
== DELETE : /api/v1/fridge/{id}
=== 냉장고 속 단일 재료 삭제

operation::fridge-delete[snippets='path-parameters,response-fields,response-body,http-request,http-response']

=== 예외 처리
1. 냉장고 id를 입력했는데, 해당하는 냉장고가 존재하지 않을 때

    "message" : "해당하는 냉장고가 존재하지 않습니다."